import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';

import {
   MatButtonModule,
   MatToolbarModule,
   MatIconModule,
   MatBadgeModule,
   MatSidenavModule,
   MatListModule,
   MatGridListModule,
   MatFormFieldModule,
   MatInputModule,
   MatSelectModule,
   MatRadioModule,
   MatDatepickerModule,
   MatNativeDateModule,
   MatChipsModule,
   MatTooltipModule,
   MatTableModule,
   MatPaginatorModule,
   MatCardModule,
   MatSnackBarModule,
   MatProgressSpinnerModule,
   MatSlideToggleModule,
   MatBottomSheetModule,
   MatDialogModule,
   MatMenuModule,
   MatCheckboxModule,
   MatStepperModule,
   MatExpansionModule,
} from '@angular/material';

@NgModule({
   imports: [
      CommonModule,
      MatButtonModule,
      MatToolbarModule,
      MatIconModule,
      MatSidenavModule,
      MatBadgeModule,
      MatListModule,
      MatGridListModule,
      MatFormFieldModule,
      MatInputModule,
      MatSelectModule,
      MatRadioModule,
      MatDatepickerModule,
      MatNativeDateModule,
      MatChipsModule,
      MatTooltipModule,
      MatTableModule,
      MatPaginatorModule,
      MatCardModule,
      MatSnackBarModule,
      MatProgressSpinnerModule,
      MatSlideToggleModule,
      MatBottomSheetModule,
      MatDialogModule,
      MatMenuModule,
      MatStepperModule,
      MatExpansionModule
   ],
   exports: [
      MatButtonModule,
      MatToolbarModule,
      MatIconModule,
      MatSidenavModule,
      MatBadgeModule,
      MatListModule,
      MatGridListModule,
      MatInputModule,
      MatFormFieldModule,
      MatSelectModule,
      MatRadioModule,
      MatDatepickerModule,
      MatChipsModule,
      MatTooltipModule,
      MatTableModule,
      MatPaginatorModule,
      MatCardModule,
      MatSnackBarModule,
      MatProgressSpinnerModule,
      MatSlideToggleModule,
      MatBottomSheetModule,
      MatDialogModule,
      MatMenuModule,
      MatCheckboxModule,
      MatStepperModule,
      MatExpansionModule
   ],
   providers: [
      MatDatepickerModule,
   ],
   schemas: [CUSTOM_ELEMENTS_SCHEMA]
})

export class AngularMaterialModule { }
